trigger:
- main

pool:
  vmImage: ubuntu-latest
variables:
  dockerComposeFile: 'docker-compose.yml'
steps:
   - task: AzureCLI@2
     inputs:
       azureSubscription: 'SubscriptionEstudos(91ed451d-ef62-4c7d-9ae8-f9b32b441784)'
       scriptType: 'bash'
       scriptLocation: 'inlineScript'
       inlineScript: |
         docker-compose -f $(dockerComposeFile) build
         az acr login --name cryptoservice --username cryptoservice --password TMw97UyrRT483MzBfNpg+Zsv3o9rjrTyYl33EpQPZd+ACRCTuJ7W
         docker-compose -f $(dockerComposeFile) push