trigger:
- main

pool:
  vmImage: ubuntu-latest
variables:
  dockerComposeFile: 'docker-compose.yml'
steps:
   - task: AzureCLI@2
     inputs:
       azureSubscription: 'SubscriptionEstudos(91ed451d-ef62-4c7d-9ae8-f9b32b441784)'
       scriptType: 'bash'
       scriptLocation: 'inlineScript'
       inlineScript: |
         docker-compose -f $(dockerComposeFile) build
         TOKEN=$(az acr login --name cryptoservice --expose-token --output tsv --query accessToken)
         docker login cryptoservice.azurecr.io --username 00000000-0000-0000-0000-000000000000 --password $TOKEN
         docker-compose -f $(dockerComposeFile) push