trigger:
- main

pool:
  vmImage: ubuntu-latest
variables:
  dockerComposeFile: 'docker-compose.yml'
steps:
      - task: DockerCompose@0
        inputs:
             containerregistrytype: 'Azure Container Registry'
             azureSubscription: 'SubscriptionEstudos(1)(91ed451d-ef62-4c7d-9ae8-f9b32b441784)'
             azureContainerRegistry: '{"loginServer":"cryptoservice.azurecr.io", "id" : "/subscriptions/91ed451d-ef62-4c7d-9ae8-f9b32b441784/resourceGroups/Estudos/providers/Microsoft.ContainerRegistry/registries/cryptoservice"}'
             dockerComposeFile: 'docker-compose.yml'
             action: 'Build services'
             includeLatestTag: true
      - task: DockerCompose@0
        inputs:
          containerregistrytype: 'Azure Container Registry'
          azureSubscription: 'SubscriptionEstudos(2)(91ed451d-ef62-4c7d-9ae8-f9b32b441784)'
          azureContainerRegistry: '{"loginServer":"cryptoservice.azurecr.io", "id" : "/subscriptions/91ed451d-ef62-4c7d-9ae8-f9b32b441784/resourceGroups/Estudos/providers/Microsoft.ContainerRegistry/registries/cryptoservice"}'
          dockerComposeFile: 'docker-compose.yml'
          action: 'Push services'
          includeLatestTag: true
      - task: KubernetesManifest@1
        inputs:
          action: 'deploy'
          connectionType: 'azureResourceManager'
          azureSubscriptionConnection: 'SubscriptionEstudos(3)(91ed451d-ef62-4c7d-9ae8-f9b32b441784)'
          azureResourceGroup: 'Estudos'
          kubernetesCluster: 'cryptoservice'