trigger:
- main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: 'c332bc41-be6e-4102-8c61-f85d0eb457c6'
  containerRegistry: 'cryptoservice.azurecr.io'
  dockerComposeFile: 'docker-compose.yml'
  vmImageName: 'ubuntu-latest'
  azureSubscription: 'SubscriptionEstudos(5)(91ed451d-ef62-4c7d-9ae8-f9b32b441784)'
  azureSubscriptionEndpoint: 'SubscriptionEstudos(5)(91ed451d-ef62-4c7d-9ae8-f9b32b441784)'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildAndDeploy
    displayName: Build and Deploy
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: '$(azureSubscription)'
        azureContainerRegistry: '{"loginServer":"$(containerRegistry)", "id" : "/subscriptions/91ed451d-ef62-4c7d-9ae8-f9b32b441784/resourceGroups/Estudos/providers/Microsoft.ContainerRegistry/registries/cryptoservice"}'
        dockerComposeFile: '$(dockerComposeFile)'
        action: 'Build services'
        includeLatestTag: true

    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: '$(azureSubscription)'
        azureContainerRegistry: '{"loginServer":"$(containerRegistry)", "id" : "/subscriptions/91ed451d-ef62-4c7d-9ae8-f9b32b441784/resourceGroups/Estudos/providers/Microsoft.ContainerRegistry/registries/cryptoservice"}'
        dockerComposeFile: '$(dockerComposeFile)'
        action: 'Push services'
        includeLatestTag: true

    - upload: manifests
      artifact: manifests

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'CryptoMicroService-1810.default'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Kubernetes@1
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: '$(azureSubscriptionEndpoint)'
              azureResourceGroup: 'Estudos'
              kubernetesCluster: 'cryptoservice'
              command: 'apply'
              arguments: '-f $(Pipeline.Workspace)/manifests/deploymentapi.yml -f $(Pipeline.Workspace)/manifests/deploymentweb.yml -f $(Pipeline.Workspace)/manifests/service.yml -f $(Pipeline.Workspace)/manifests/serviceweb.yml'
              secretType: 'dockerRegistry'
              containerRegistryType: 'Azure Container Registry'
