apiVersion: apps/v1
kind: Deployment
metadata:
  name: cryptoweb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cryptoweb
  template:
    metadata:
      labels:
        app: cryptoweb
    spec:
      containers:
        - name: cryptoweb
          image: cryptoservice.azurecr.io/cryptoweb
          ports:
            - containerPort: 86
