apiVersion: apps/v1
kind: Deployment
metadata:
  name: cryptomicroservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cryptomicroservice
  template:
    metadata:
      labels:
        app: cryptomicroservice
    spec:
      containers:
        - name: cryptoapi
          image: cryptoservice.azurecr.io/cryptoapi
          ports:
            - containerPort: 80
        - name: cryptoweb
          image: cryptoservice.azurecr.io/cryptoweb
          ports:
            - containerPort: 86
